spring.application.name=Product
spring.datasource.url=jdbc:postgresql://localhost:5432/productreview
spring.datasource.username= postgres
spring.datasource.password=ayana
spring.jpa.hibernate.ddl-auto=update
